version: '3'
services:
  app:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  db:
    image: yzh44yzh/wg_forge_backend_env:1.1
    ports:
      - 5432:5432
