version: '3'
services:
  app:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=your_postgres_user
      - POSTGRES_PASSWORD=your_postgres_password
      - POSTGRES_DB=your_postgres_db
    command: uvicorn main:app --host 0.0.0.0 --port 8000
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=your_postgres_user
      - POSTGRES_PASSWORD=your_postgres_password
      - POSTGRES_DB=your_postgres_db